version: '3.9'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  sprint-planner:
    build:
      context: ..
      dockerfile: ./Dockerfile
    restart: always
    container_name: np-logger-service
    depends_on:
      - postgresdb
    expose:
      - ${LOG_SERVICE_PORT}
    environment:
      - ADDRESS=${LOG_SERVICE_ADDRESS}
      - PORT=${LOG_SERVICE_PORT}



    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/