version: '3.9'

services:

  sprint-planner:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_BACKEND=${REACT_APP_BACKEND}
    restart: always
    container_name: sprint-planner
    environment:
      - SERVER_ADDRESS=${SERVER_ADDRESS}
    ports:
      - ${SERVER_EXTERNAL_PORT}:8000
    networks:
      sprint-planner:
        ipv4_address: ${SERVER_ADDRESS}
networks:
  sprint-planner:
    ipam:
      driver: default
      config:
        - subnet: "172.20.200.0/24"
