version: '3.9'

services:

  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 8082:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   networks:
  #     sprint-planner:
  #       ipv4_address: ${MONGO_ADDRESS}

  sprint-planner:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_BACKEND=${REACT_APP_BACKEND}
    restart: always
    container_name: sprint-planner
    # depends_on:
    #   - mongo
    ports:
      - ${SERVER_EXTERNAL_PORT}:8000
    networks:
      sprint-planner:
        ipv4_address: ${SERVER_ADDRESS}
networks:
  sprint-planner:
    ipam:
      driver: default
      config:
        - subnet: "172.20.200.0/24"
